package com.alight.marketplace.modules.settlement.entity;

public enum SettlementStatus {
    SETTLEMENT_CREATED,
    SETTLEMENT_CALCULATED,
    SETTLEMENT_ELIGIBILITY_EVALUATION,
    SETTLEMENT_ELIGIBLE,
    SETTLEMENT_PENDING_APPROVAL,
    SETTLEMENT_APPROVED,
    SETTLEMENT_COMPLETED,
    SETTLEMENT_ON_HOLD,
    SETTLEMENT_REVERSED,
    SETTLEMENT_ADJUSTED,
    SETTLEMENT_DISPUTED,

    // Database / API Short Forms
    CREATED,
    CALCULATED,
    ELIGIBILITY_EVALUATION,
    ELIGIBLE,
    APPROVED,
    SETTLED,
    ON_HOLD,
    REVERSED,
    ADJUSTED,
    DISPUTED
}
