server:
  port: 0

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:alight_test_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-expiration-ms: 3600000
    refresh-expiration-ms: 86400000
  cors:
    allowed-origins: http://localhost:3000
